#! /bin/bash

mysql -uroot -ppassword -e "DROP DATABASE keystone"
mysql -uroot -ppassword -e "DROP DATABASE key1"
mysql -uroot -ppassword -e "DROP DATABASE key2"
mysql -uroot -ppassword -e "DROP DATABASE key3"
./db-showDBs
