#! /bin/bash 

echo "Dump dummy data into keystone db"
mysql -uroot -ppassword -e "CREATE DATABASE keystone"
mysql -uroot -ppassword keystone < keystone-dummy.db
mysql -uroot -ppassword keystone -e "select * from user"
